org_zh = [
    #50个常见国际组织
    "联合国","联合国大会","联合国安全理事会","联合国经济及社会理事会","联合国秘书处",
    "联合国儿童基金会","联合国开发计划署","联合国环境规划署","联合国人口基金","联合国难民署",
    "联合国人权理事会","联合国粮食及农业组织","联合国教育、科学及文化组织","世界卫生组织",
    "国际劳工组织","世界气象组织","世界知识产权组织","国际电信联盟","国际海事组织",
    "国际原子能机构","世界银行","国际货币基金组织","世界贸易组织","经济合作与发展组织",
    "二十国集团","七国集团","亚太经济合作组织","上海合作组织","东南亚国家联盟","欧洲联盟",
    "欧洲委员会","欧洲议会","欧洲中央银行","北大西洋公约组织","美洲国家组织","非洲联盟",
    "阿拉伯国家联盟","海湾合作委员会","伊斯兰合作组织","金砖国家","国际红十字与红新月运动",
    "国际红十字委员会","红十字会与红新月会国际联合会","国际刑警组织","国际奥林匹克委员会",
    "国际足球联合会","世界自然基金会","绿色和平组织","国际特赦组织","透明国际",

    #500所大学
    "麻省理工学院","剑桥大学","牛津大学","哈佛大学","斯坦福大学","帝国理工学院","苏黎世联邦理工学院",
    "新加坡国立大学","伦敦大学学院","加州大学伯克利分校","芝加哥大学","宾夕法尼亚大学","康奈尔大学",
    "墨尔本大学","加州理工学院","耶鲁大学","清华大学","北京大学","普林斯顿大学","新南威尔士大学",
    "悉尼大学","多伦多大学","爱丁堡大学","哥伦比亚大学","香港大学","南洋理工大学","巴黎科学艺术人文大学",
    "洛桑联邦理工学院","曼彻斯特大学","伦敦国王学院","蒙纳士大学","东京大学","首尔大学","密歇根大学",
    "香港中文大学","复旦大学","西北大学","加州大学洛杉矶分校","上海交通大学","多伦多大学密西沙加分校",
    "浙江大学","京都大学","代尔夫特理工大学","卡耐基梅隆大学","香港科技大学","哥本哈根大学",
    "德克萨斯大学奥斯汀分校","布朗大学","华威大学","巴黎萨克雷大学","慕尼黑工业大学","鲁汶大学","阿姆斯特丹大学",
    "伯明翰大学","布里斯托大学","东京工业大学","海德堡大学","奥克兰大学","隆德大学","格拉斯哥大学","杜伦大学",
    "伊利诺伊大学厄巴纳—香槟分校","华盛顿大学","澳大利亚国立大学","利兹大学","伯尔尼大学","伯尔尼大学医院学院",
    "阿尔伯塔大学","诺丁汉大学","谢菲尔德大学","巴塞罗那大学","日内瓦大学","南京大学","武汉大学","南安普敦大学",
    "赫尔辛基大学","波士顿大学","俄亥俄州立大学","麦吉尔大学","伯明翰大学学院","爱荷华大学","普渡大学","达特茅斯学院",
    "加州大学圣地亚哥分校","圣安德鲁斯大学","香港城市大学","昆士兰大学","阿德莱德大学","宾夕法尼亚州立大学",
    "巴黎第一大学","巴黎综合理工学院","米兰理工大学","威斯康星大学麦迪逊分校","柏林洪堡大学","弗莱堡大学","哥廷根大学","乌得勒支大学",
    "莱顿大学","乌得勒支大学","瓦格宁根大学","格罗宁根大学","阿姆斯特丹自由大学","鹿特丹伊拉斯姆斯大学","马斯特里赫特大学",
    "蒂尔堡大学","特文特大学","埃因霍温理工大学","代尔夫特理工大学","巴黎第一大学","巴黎第二大学","巴黎第三大学","巴黎第四大学",
    "巴黎第五大学","巴黎第六大学","巴黎第七大学","巴黎第八大学","巴黎第九大学","巴黎第十大学","巴黎第十一大学","巴黎第十二大学",
    "巴黎第十三大学","巴黎萨克雷大学","巴黎高等师范学院","巴黎综合理工学院","格勒诺布尔大学","里昂大学","里尔大学","波尔多大学",
    "图卢兹大学","马赛大学","尼斯大学","南特大学","雷恩大学","斯特拉斯堡大学","蒙彼利埃大学","柏林自由大学","柏林工业大学",
    "柏林洪堡大学","慕尼黑大学","海德堡大学","汉堡大学","科隆大学","法兰克福大学","波恩大学","斯图加特大学",
    "达姆施塔特工业大学","亚琛工业大学","卡尔斯鲁厄理工学院","不来梅大学","杜伊斯堡埃森大学","汉诺威大学","莱比锡大学","耶拿大学",
    "哥廷根大学","弗莱堡大学","图宾根大学","曼海姆大学","萨尔大学","维也纳大学","维也纳工业大学","格拉茨大学","格拉茨工业大学",
    "因斯布鲁克大学","林茨大学","萨尔茨堡大学","苏黎世大学","巴塞尔大学","伯尔尼大学","洛桑大学","日内瓦大学",
    "马德里康普顿斯大学","马德里自治大学","马德里理工大学","巴塞罗那大学","巴塞罗那自治大学","庞培法布拉大学",
    "瓦伦西亚大学","萨拉曼卡大学","塞维利亚大学","格拉纳达大学","马拉加大学","萨拉戈萨大学","米兰大学","米兰理工大学","博洛尼亚大学",
    "帕多瓦大学","比萨大学","罗马第一大学","罗马第二大学","那不勒斯费德里科二世大学","都灵大学","佛罗伦萨大学","卡塔尼亚大学","帕维亚大学",
    "特伦托大学","维罗纳大学","根特大学","鲁汶大学","布鲁塞尔自由大学","安特卫普大学","列日大学","奥斯陆大学","卑尔根大学","挪威科技大学",
    "乌普萨拉大学","隆德大学","斯德哥尔摩大学","查尔姆斯理工大学","卡罗林斯卡学院","赫尔辛基大学","阿尔托大学","图尔库大学","奥胡斯大学",
    "南丹麦大学","哥本哈根大学","哥本哈根商学院","冰岛大学","华沙大学","华沙理工大学","雅盖隆大学","克拉科夫工业大学","布拉格查理大学",
    "捷克理工大学","马萨里克大学","布达佩斯罗兰大学","布达佩斯技术经济大学","贝尔格莱德大学","萨格勒布大学","卢布尔雅那大学","索非亚大学",
    "雅典大学","雅典国立理工大学","塞萨洛尼基亚里士多德大学","伊斯坦布尔大学","中东技术大学","博阿齐奇大学","安卡拉大学","科奇大学",
    "萨班哲大学","特拉维夫大学","耶路撒冷希伯来大学","魏茨曼科学研究所","海法大学","巴伊兰大学","开罗大学","亚历山大大学","开罗美国大学",
    "开普敦大学","威特沃特斯兰德大学","斯坦陵布什大学","夸祖鲁纳塔尔大学","约翰内斯堡大学","比勒陀利亚大学","麦吉尔大学","英属哥伦比亚大学",
    "滑铁卢大学","西安大略大学","麦克马斯特大学","阿尔伯塔大学","卡尔加里大学","维多利亚大学","约克大学","渥太华大学","康考迪亚大学","拉瓦尔大学",
    "魁北克大学蒙特利尔分校","达尔豪斯大学","萨斯喀彻温大学","曼尼托巴大学","多伦多大学士嘉堡分校","多伦多大学密西沙加分校","乔治城大学",
    "乔治华盛顿大学","莱斯大学","范德堡大学","埃默里大学","塔夫茨大学","罗切斯特大学","匹兹堡大学","明尼苏达大学双城分校",
    "印第安纳大学布卢明顿分校","密歇根州立大学","马里兰大学学院公园分校","弗吉尼亚大学","北卡罗来纳大学教堂山分校","德克萨斯农工大学",
    "佛罗里达大学","亚利桑那州立大学","亚利桑那大学","科罗拉多大学博尔德分校","俄勒冈大学","华盛顿州立大学","犹他大学","夏威夷大学马诺阿分校",
    "普渡大学","宾夕法尼亚州立大学","威斯康星大学麦迪逊分校","波士顿大学","布兰戴斯大学","凯斯西储大学","日本东北大学","德雷塞尔大学",
    "纽约州立大学石溪分校","纽约州立大学布法罗分校","纽约州立大学宾汉姆顿分校","香港理工大学","香港城市大学","香港浸会大学","岭南大学","澳门大学",
    "大阪大学","名古屋大学","中国东北大学","九州大学","北海道大学","筑波大学","早稻田大学","庆应义塾大学","神户大学",
    "广岛大学","千叶大学","横滨国立大学","东京医科齿科大学","大阪市立大学","大阪府立大学","首尔大学","延世大学","高丽大学","成均馆大学",
    "汉阳大学","庆熙大学","中央大学","韩国科学技术院","浦项科技大学","新加坡管理大学","南洋理工大学","新加坡国立大学","马来亚大学",
    "马来西亚国立大学","马来西亚博特拉大学","马来西亚理科大学","马来西亚理工大学","泰国朱拉隆功大学","玛希隆大学","清迈大学","北京师范大学",
    "天津大学","西安交通大学","华中科技大学","山东大学","厦门大学","四川大学","南开大学","东南大学","华南理工大学","大连理工大学","湖南大学",
    "中南大学","电子科技大学","哈尔滨工程大学","北京理工大学","中国人民大学","吉林大学","兰州大学","重庆大学","西北工业大学","中国农业大学",
    "南京理工大学","南京航空航天大学","北京航空航天大学","中国海洋大学","上海大学","苏州大学","暨南大学","华东师范大学","华东理工大学",
    "北京交通大学","北京邮电大学","上海财经大学","上海外国语大学","北京外国语大学","复旦大学上海医学院","中山大学","南方科技大学","深圳大学",
    "香港教育大学","阿德莱德大学","昆士兰大学","西澳大学","悉尼科技大学","皇家墨尔本理工大学","迪肯大学","昆士兰科技大学","格里菲斯大学",
    "纽卡斯尔大学","塔斯马尼亚大学","拉筹伯大学","麦考瑞大学","卧龙岗大学","科廷大学","南澳大学",

    #500家公司
    "沃尔玛","沙特阿美公司","国家电网有限公司","亚马逊公司","中国石油天然气集团有限公司","中国石油化工集团有限公司","埃克森美孚公司","苹果公司",
    "壳牌公司","联合健康集团","CVS健康公司","伯克希尔·哈撒韦公司","Alphabet公司","麦克森公司","丰田汽车公司","嘉能可公司","特拉福图拉集团",
    "中国建筑集团有限公司","三星电子","开市客公司","鸿海精密工业股份有限公司","中国工商银行","中国建设银行","中国农业银行","中国银行","微软公司",
    "中国平安保险（集团）股份有限公司","中国移动通信集团有限公司","中国铁路工程集团有限公司","中国铁道建筑集团有限公司","大众汽车集团",
    "中国海洋石油集团有限公司","中国人寿保险（集团）公司","中国中化控股有限责任公司","中国宝武钢铁集团有限公司","美国电话电报公司","道达尔能源公司",
    "福特汽车公司","梅赛德斯-奔驰集团","中国交通建设集团有限公司","本田汽车公司","中国中信集团有限公司","中国华润有限公司","法国电力公司",
    "俄罗斯天然气工业股份公司","德国电信股份公司","宝马集团","中国南方电网有限责任公司","中国邮政集团有限公司","中国电力建设集团有限公司",
    "中国能源建设集团有限公司","沃博联","京东集团","克罗格公司","中国五矿集团有限公司","中国兵器工业集团有限公司","房利美","中国中车集团有限公司",
    "中国联合网络通信集团有限公司","塔吉特公司","安联保险集团","中国电子科技集团有限公司","中国远洋海运集团有限公司","中国航天科技集团有限公司",
    "中国航空工业集团有限公司","中国航天科工集团有限公司","中国电子信息产业集团有限公司","英杰华集团","日本电报电话公司","中国中煤能源集团有限公司",
    "中国华能集团有限公司","中国华电集团有限公司","中国大唐集团有限公司","中国国电集团有限公司","中国广核集团有限公司","中国长江三峡集团有限公司",
    "中国节能环保集团有限公司","中国诚通控股集团有限公司","中国国新控股有限责任公司","中国有色矿业集团有限公司","中国黄金集团有限公司","中国林业集团有限公司",
    "中国南方航空集团有限公司","中国东方航空集团有限公司","中国航空集团有限公司","中国通用技术（集团）控股有限责任公司","中国保利集团有限公司",
    "中国旅游集团有限公司","中国医药集团有限公司","中国机械工业集团有限公司","中国建材集团有限公司","中国中钢集团有限公司","中国铝业集团有限公司",
    "中国化学工程集团有限公司","中国中冶集团有限公司","中国盐业集团有限公司","中国物流集团有限公司","中国储备粮管理集团有限公司",
    "摩根大通公司","美国银行","中国光大集团股份公司","中国太平保险集团有限责任公司","中国人民保险集团股份有限公司","中国再保险（集团）股份有限公司",
    "中国光大银行股份有限公司","中国民生银行股份有限公司","中国邮政储蓄银行股份有限公司","交通银行股份有限公司","上海浦东发展银行股份有限公司",
    "兴业银行股份有限公司","招商银行股份有限公司","中信银行股份有限公司","华夏银行股份有限公司","北京银行股份有限公司","上海银行股份有限公司",
    "江苏银行股份有限公司","南京银行股份有限公司","宁波银行股份有限公司","广州银行股份有限公司","渤海银行股份有限公司","天津银行股份有限公司",
    "哈尔滨银行股份有限公司","盛京银行股份有限公司","重庆银行股份有限公司","成都银行股份有限公司","长沙银行股份有限公司","徽商银行股份有限公司",
    "青岛银行股份有限公司","郑州银行股份有限公司","兰州银行股份有限公司","西安银行股份有限公司","贵阳银行股份有限公司","昆仑银行股份有限公司",
    "大连银行股份有限公司","吉林银行股份有限公司","包商银行股份有限公司","锦州银行股份有限公司","恒丰银行股份有限公司","渣打集团","汇丰控股有限公司",
    "巴克莱银行","德意志银行","法国巴黎银行","瑞士银行集团","瑞士信贷集团","荷兰国际集团","意大利联合圣保罗银行","西班牙桑坦德银行","西班牙对外银行",
    "瑞穗金融集团","三菱日联金融集团","三井住友金融集团","野村控股株式会社","第一生命控股株式会社","东京海上控股株式会社","日本邮政控股公司",
    "日本生命保险公司","住友生命保险公司","明治安田生命保险公司","富国银行","高盛集团","摩根士丹利","花旗集团","美国运通公司","美国国际集团",
    "美国大都会人寿保险公司","保德信金融集团","信诺集团","安盛集团","忠利保险集团","慕尼黑再保险公司","苏黎世保险集团","保诚集团","友邦保险控股有限公司",
    "中国太平洋保险（集团）股份有限公司","新华人寿保险股份有限公司","泰康保险集团股份有限公司","阳光保险集团股份有限公司","中国华融资产管理股份有限公司",
    "中国信达资产管理股份有限公司","中国东方资产管理股份有限公司","中国长城资产管理股份有限公司","国泰君安证券股份有限公司","中信证券股份有限公司",
    "海通证券股份有限公司","华泰证券股份有限公司","招商证券股份有限公司","申万宏源集团股份有限公司","广发证券股份有限公司","东方证券股份有限公司",
    "中金公司","光大证券股份有限公司","国信证券股份有限公司","平安证券股份有限公司","银河证券股份有限公司","东兴证券股份有限公司","英特尔公司",
    "英伟达公司","甲骨文公司","思科系统公司","高通公司","博通公司","戴尔科技公司","惠普公司","国际商业机器公司","Adobe公司","德州仪器公司",
    "应用材料公司","美光科技公司","ASML控股公司","台积电","联发科技股份有限公司","索尼集团","松下控股株式会社","日立制作所","东芝公司",
    "三菱电机株式会社","富士通株式会社","佳能株式会社","理光株式会社","爱普生公司","LG电子","SK海力士","现代汽车集团","起亚公司","雷诺集团",
    "标致雪铁龙集团","沃尔沃集团","沃尔沃汽车公司","塔塔汽车公司","铃木株式会社","马自达汽车公司","斯巴鲁株式会社","长城汽车股份有限公司",
    "吉利汽车控股有限公司","比亚迪股份有限公司","上汽集团","广汽集团","东风汽车集团有限公司","一汽集团","北汽集团","蔚来汽车","小鹏汽车",
    "理想汽车","特斯拉公司","波音公司","空中客车公司","洛克希德·马丁公司","雷神技术公司","诺斯罗普·格鲁曼公司","通用动力公司","霍尼韦尔国际公司",
    "3M公司","卡特彼勒公司","迪尔公司","西门子股份公司","通用电气公司","施耐德电气","ABB集团","飞利浦公司","松下电器产业株式会社","日立能源",
    "艾默生电气公司","伊顿公司","罗克韦尔自动化公司","丹纳赫公司","赛默飞世尔科技公司","百事公司","可口可乐公司","雀巢公司","宝洁公司","联合利华公司",
    "欧莱雅集团","雅诗兰黛公司","耐克公司","阿迪达斯公司","彪马公司","迅销公司","开云集团","路威酩轩集团","香奈儿公司","宜家公司","家得宝公司",
    "劳氏公司","塔吉特公司","沃尔格林博姿联盟公司","百思买公司","麦当劳公司","百胜餐饮集团","星巴克公司","达美乐比萨公司","百威英博公司","喜力啤酒公司",
    "嘉士伯集团","帝亚吉欧公司","保乐力加集团","美敦力公司","雅培公司","强生公司","辉瑞公司","默沙东公司","阿斯利康公司","葛兰素史克公司","诺华公司",
    "罗氏公司","礼来公司","拜耳集团","赛诺菲公司","武田制药公司","安进公司","百健公司","吉利德科学公司","再生元制药公司","赛默飞世尔科技公司","丹纳赫公司",
    "Illumina公司","沃博联公司","沃尔格林公司","CVS健康公司","麦克森公司","美源伯根公司","康德乐公司","联合包裹服务公司","联邦快递公司","德国邮政敦豪集团",
    "日本邮政控股公司","顺丰控股股份有限公司","中通快递股份有限公司","圆通速递股份有限公司","申通快递股份有限公司","韵达控股股份有限公司",
    "德邦物流股份有限公司","京东物流股份有限公司","菜鸟网络科技有限公司","阿里巴巴集团控股有限公司","腾讯控股有限公司","字节跳动有限公司","百度公司",
    "小米集团","美团公司","拼多多公司","网易公司","哔哩哔哩公司","滴滴出行科技有限公司","Grab控股公司","Sea有限公司","Booking控股公司","Airbnb公司",
    "优步科技公司","Lyft公司","Expedia集团","Trip.com集团","携程集团","万豪国际集团","希尔顿全球控股公司","洲际酒店集团","雅高集团","凯悦酒店集团",
    "温德姆酒店集团","香格里拉集团","复星国际有限公司","绿地控股集团股份有限公司","碧桂园控股有限公司","万科企业股份有限公司","恒大集团","龙湖集团",
    "华润置地有限公司","保利发展控股集团股份有限公司","招商蛇口工业区控股股份有限公司","世茂集团控股有限公司","融创中国控股有限公司","远洋集团控股有限公司",
    "雅居乐集团控股有限公司","旭辉控股集团有限公司","中梁控股集团有限公司","宝龙地产控股有限公司","金地（集团）股份有限公司","建发房地产集团有限公司",
    "越秀地产股份有限公司","合景泰富集团控股有限公司","中国奥园集团股份有限公司","新城控股集团股份有限公司","中国金茂控股集团有限公司","中国海外发展有限公司",
    "华侨城集团有限公司","首创集团有限公司","首开集团有限公司","光明食品（集团）有限公司","中粮集团有限公司","益海嘉里集团","蒙牛乳业有限公司","伊利集团",
    "娃哈哈集团有限公司","农夫山泉股份有限公司","统一企业中国控股有限公司","康师傅控股有限公司",
]

org_es = [
    #50个常见国际组织
    "Organización de las Naciones Unidas","Asamblea General de las Naciones Unidas","Consejo de Seguridad de las Naciones Unidas",
    "Consejo Económico y Social de las Naciones Unidas","Secretaría de las Naciones Unidas",
    "Programa de las Naciones Unidas para el Desarrollo","Programa de las Naciones Unidas para el Medio Ambiente",
    "Fondo de Población de las Naciones Unidas","Alto Comisionado de las Naciones Unidas para los Refugiados",
    "Consejo de Derechos Humanos de las Naciones Unidas","Organización de las Naciones Unidas para la Alimentación y la Agricultura",
    "Organización de las Naciones Unidas para la Educación, la Ciencia y la Cultura","Organización Mundial de la Salud",
    "Organización Internacional del Trabajo","Organización Meteorológica Mundial","Organización Mundial de la Propiedad Intelectual",
    "Unión Internacional de Telecomunicaciones","Organización Marítima Internacional","Organismo Internacional de Energía Atómica",
    "Banco Mundial","Fondo Monetario Internacional","Organización Mundial del Comercio",
    "Organización para la Cooperación y el Desarrollo Económicos","Grupo de los Veinte","Grupo de los Siete",
    "Foro de Cooperación Económica Asia-Pacífico","Organización de Cooperación de Shanghái","Asociación de Naciones del Sudeste Asiático",
    "Unión Europea","Consejo de Europa","Parlamento Europeo","Banco Central Europeo","Organización del Tratado del Atlántico Norte",
    "Organización de los Estados Americanos","Unión Africana","Liga de los Estados Árabes","Consejo de Cooperación del Golfo",
    "Organización de Cooperación Islámica","BRICS","Movimiento Internacional de la Cruz Roja y de la Media Luna Roja",
    "Comité Internacional de la Cruz Roja","Federación Internacional de Sociedades de la Cruz Roja y de la Media Luna Roja",
    "Interpol","Comité Olímpico Internacional","Federación Internacional de Fútbol Asociación","Fondo Mundial para la Naturaleza",
    "Greenpeace","Amnistía Internacional","Transparencia Internacional",

    #500所大学
    "Instituto Tecnológico de Massachusetts","Universidad de Cambridge","Universidad de Oxford","Universidad de Harvard",
    "Universidad de Stanford","Imperial College de Londres","Escuela Politécnica Federal de Zúrich","Universidad Nacional de Singapur",
    "University College de Londres","Universidad de California en Berkeley","Universidad de Chicago","Universidad de Pensilvania",
    "Universidad Cornell","Universidad de Melbourne","Instituto de Tecnología de California","Universidad de Yale","Universidad Tsinghua",
    "Universidad de Pekín","Universidad de Princeton","Universidad de Nueva Gales del Sur","Universidad de Sídney","Universidad de Toronto",
    "Universidad de Edimburgo","Universidad de Columbia","Universidad de Hong Kong","Universidad Tecnológica de Nanyang",
    "Universidad PSL de París","Escuela Politécnica Federal de Lausana","Universidad de Manchester","King's College de Londres",
    "Universidad Monash","Universidad de Tokio","Universidad Nacional de Seúl","Universidad de Michigan","Universidad China de Hong Kong",
    "Universidad Fudan","Universidad Northwestern","Universidad de California en Los Ángeles","Universidad Jiao Tong de Shanghái",
    "Universidad de Zhejiang","Universidad de Kioto","Universidad Tecnológica de Delft","Universidad Carnegie Mellon",
    "Universidad de Ciencia y Tecnología de Hong Kong","Universidad de Copenhague","Universidad de Texas en Austin","Universidad Brown",
    "Universidad de Warwick","Universidad Paris-Saclay","Universidad Técnica de Múnich","Universidad KU Leuven","Universidad de Ámsterdam",
    "Universidad de Birmingham","Universidad de Bristol","Instituto Tecnológico de Tokio","Universidad de Heidelberg","Universidad de Auckland",
    "Universidad de Lund","Universidad de Glasgow","Universidad de Durham","Universidad de Illinois en Urbana-Champaign",
    "Universidad de Washington","Universidad Nacional de Australia","Universidad de Leeds","Universidad de Berna","Universidad de Alberta",
    "Universidad de Nottingham","Universidad de Sheffield","Universidad de Barcelona","Universidad de Ginebra","Universidad de Nankín",
    "Universidad de Wuhan","Universidad de Southampton","Universidad de Helsinki","Universidad de Boston","Universidad Estatal de Ohio",
    "Universidad McGill","Universidad Purdue","Dartmouth College","Universidad de California en San Diego","Universidad de St Andrews",
    "Universidad de Malaya","Universidad de la Ciudad de Hong Kong","Universidad de Queensland","Universidad de Adelaida",
    "Universidad Estatal de Pensilvania","Escuela Politécnica","Universidad de Milán","Universidad de Wisconsin-Madison",
    "Universidad Humboldt de Berlín","Universidad de Friburgo","Universidad de Gotinga","Universidad de Utrecht","Universidad de Leiden",
    "Universidad Erasmus de Róterdam","Universidad de Wageningen","Universidad de Groningen","Vrije Universiteit de Ámsterdam",
    "Universidad de Maastricht","Universidad de Tilburg","Universidad de Twente","Universidad Tecnológica de Eindhoven",
    "Universidad Paris I Panthéon-Sorbonne","Universidad Paris II Panthéon-Assas","Universidad Paris III Sorbonne Nouvelle",
    "Universidad Paris IV Sorbonne","Universidad Paris V René Descartes","Universidad Paris VI Pierre y Marie Curie",
    "Universidad Paris VII Denis Diderot","Universidad Paris VIII Vincennes-Saint-Denis","Universidad Paris IX Dauphine",
    "Universidad Paris X Nanterre","Universidad Paris XI","Universidad de Grenoble Alpes","Universidad de Lyon","Universidad de Lille",
    "Universidad de Burdeos","Universidad de Toulouse","Universidad de Aix-Marsella","Universidad de Niza Sophia Antipolis",
    "Universidad de Nantes","Universidad de Rennes","Universidad de Estrasburgo","Universidad de Montpellier","Universidad Libre de Berlín",
    "Universidad Técnica de Berlín","Universidad Ludwig Maximilian de Múnich","Universidad de Hamburgo","Universidad de Colonia",
    "Universidad Goethe de Fráncfort","Universidad de Bonn","Universidad de Stuttgart","Universidad Técnica de Darmstadt",
    "Universidad Técnica de Aquisgrán","Instituto Tecnológico de Karlsruhe","Universidad de Bremen","Universidad de Duisburgo-Essen",
    "Universidad Leibniz de Hannover","Universidad de Leipzig","Universidad Friedrich Schiller de Jena","Universidad de Friburgo",
    "Universidad de Tubinga","Universidad de Mannheim","Universidad del Sarre","Universidad de Viena","Universidad Técnica de Viena",
    "Universidad de Graz","Universidad Técnica de Graz","Universidad de Innsbruck","Universidad Johannes Kepler de Linz",
    "Universidad de Salzburgo","Universidad de Zúrich","Universidad de Basilea","Universidad de Lausana","Universidad Complutense de Madrid",
    "Universidad Autónoma de Madrid","Universidad Politécnica de Madrid","Universidad Autónoma de Barcelona","Universidad Pompeu Fabra",
    "Universidad de Valencia","Universidad de Salamanca","Universidad de Sevilla","Universidad de Granada","Universidad de Málaga",
    "Universidad de Zaragoza","Universidad de Milán","Universidad de Bolonia","Universidad de Padua","Universidad de Pisa",
    "Universidad de Roma La Sapienza","Universidad de Roma Tor Vergata","Universidad Federico II de Nápoles","Universidad de Turín",
    "Universidad de Florencia","Universidad de Catania","Universidad de Pavía","Universidad de Trento","Universidad de Verona",
    "Universidad de Gante","Universidad de Oslo","Universidad de Bergen","Universidad Noruega de Ciencia y Tecnología","Universidad de Uppsala",
    "Universidad de Estocolmo","Instituto Karolinska","Universidad de Turku","Universidad de Aarhus","Universidad del Sur de Dinamarca",
    "Universidad de Islandia","Universidad de Varsovia","Universidad Jaguelónica de Cracovia","Universidad Carolina de Praga",
    "Universidad Masaryk","Universidad Eötvös Loránd de Budapest","Universidad de Belgrado","Universidad de Zagreb",
    "Universidad de Liubliana","Universidad de Sofía San Clemente de Ohrid","Universidad Nacional y Kapodistríaca de Atenas",
    "Universidad Técnica Nacional de Atenas","Universidad Aristóteles de Tesalónica","Universidad de Estambul",
    "Universidad Técnica de Oriente Medio","Universidad Boğaziçi","Universidad de Ankara","Universidad Koç","Universidad Sabancı",
    "Universidad de Tel Aviv","Universidad Hebrea de Jerusalén","Instituto Weizmann de Ciencias","Universidad de Haifa",
    "Universidad Bar-Ilan","Universidad de El Cairo","Universidad de Alejandría","Universidad Americana de El Cairo",
    "Universidad de Ciudad del Cabo","Universidad de Witwatersrand","Universidad de Stellenbosch","Universidad de KwaZulu-Natal",
    "Universidad de Johannesburgo","Universidad de Pretoria","Universidad de Columbia Británica","Universidad de Waterloo",
    "Universidad de Ontario Occidental","Universidad McMaster","Universidad de Ottawa","Universidad de Victoria","Universidad de York",
    "Universidad Concordia","Universidad Laval","Universidad de Dalhousie","Universidad de Saskatchewan","Universidad de Manitoba",
    "Universidad de Georgetown","Universidad George Washington","Universidad Rice","Universidad Vanderbilt","Universidad Emory",
    "Universidad Tufts","Universidad de Rochester","Universidad de Pittsburgh","Universidad de Minnesota Twin Cities",
    "Universidad de Indiana Bloomington","Universidad Estatal de Míchigan","Universidad de Maryland College Park","Universidad de Virginia",
    "Universidad de Carolina del Norte en Chapel Hill","Universidad Texas A&M","Universidad de Florida","Universidad Estatal de Arizona",
    "Universidad de Arizona","Universidad de Colorado en Boulder","Universidad de Oregón","Universidad Estatal de Washington",
    "Universidad de Utah","Universidad de Hawái en Mānoa","Universidad de Pensilvania Estatal","Universidad Brandeis",
    "Universidad Case Western Reserve","Universidad Northeastern","Universidad Drexel","Universidad Estatal de Nueva York en Stony Brook",
    "Universidad Estatal de Nueva York en Buffalo","Universidad Estatal de Nueva York en Binghamton","Universidad Politécnica de Hong Kong",
    "Universidad Bautista de Hong Kong","Universidad Lingnan","Universidad de Macao","Universidad de Osaka","Universidad de Nagoya",
    "Universidad de Tohoku","Universidad de Kyushu","Universidad de Hokkaido","Universidad de Tsukuba","Universidad Waseda","Universidad Keio",
    "Universidad de Kobe","Universidad de Hiroshima","Universidad de Chiba","Universidad Nacional de Yokohama",
    "Universidad Médica y Dental de Tokio","Universidad Metropolitana de Osaka","Universidad de Seúl","Universidad Yonsei","Universidad Korea",
    "Universidad Sungkyunkwan","Universidad Hanyang","Universidad Kyung Hee","Universidad Chung-Ang",
    "Instituto Avanzado de Ciencia y Tecnología de Corea","Instituto de Ciencia y Tecnología de Pohang","Universidad de Gestión de Singapur",
    "Universidad de Malaya","Universidad Nacional de Malasia","Universidad Putra de Malasia","Universidad de Ciencia de Malasia",
    "Universidad Tecnológica de Malasia","Universidad Chulalongkorn","Universidad Mahidol","Universidad de Chiang Mai",
    "Universidad Normal de Pekín","Universidad de Tianjin","Universidad Xi’an Jiaotong","Universidad de Ciencia y Tecnología de Huazhong",
    "Universidad de Shandong","Universidad de Xiamen","Universidad de Sichuan","Universidad de Nankai","Universidad del Sureste",
    "Universidad Tecnológica del Sur de China","Universidad Tecnológica de Dalian","Universidad de Hunan","Universidad Central del Sur",
    "Universidad de Ciencia y Tecnología Electrónica de China","Instituto Tecnológico de Harbin","Instituto de Tecnología de Pekín",
    "Universidad Renmin de China","Universidad de Jilin","Universidad de Lanzhou","Universidad de Chongqing",
    "Universidad Politécnica del Noroeste","Universidad Agrícola de China","Universidad de Ciencia y Tecnología de Nanjing",
    "Universidad de Aeronáutica y Astronáutica de Nanjing","Universidad de Aeronáutica y Astronáutica de Pekín",
    "Universidad Oceánica de China","Universidad de Shanghái","Universidad de Soochow","Universidad de Jinan",
    "Universidad Normal del Este de China","Universidad de Ciencia y Tecnología del Este de China","Universidad Jiaotong de Pekín",
    "Universidad de Correos y Telecomunicaciones de Pekín","Universidad de Finanzas y Economía de Shanghái",
    "Universidad de Estudios Internacionales de Shanghái","Universidad de Estudios Extranjeros de Pekín",
    "Universidad de Ciencia y Tecnología del Sur","Universidad de Shenzhen","Universidad Tecnológica de Sídney",
    "Universidad Tecnológica de Queensland","Universidad RMIT","Universidad Deakin","Universidad Griffith","Universidad de Newcastle",
    "Universidad de Tasmania","Universidad La Trobe","Universidad Macquarie","Universidad de Wollongong","Universidad Curtin",
    "Universidad de Australia Meridional","Universidad de Ciencia y Tecnología de Hong Kong",
    "Universidad de Ciencia y Tecnología del Sur de China","Universidad de Ciencia y Tecnología del Sur","Universidad Tecnológica de Nanyang",
    "Universidad Nacional de Singapur","Universidad de Ciencia y Tecnología Rey Abdalá","Universidad Rey Saud","Universidad Rey Abdulaziz",
    "Universidad del Petróleo y Minerales Rey Fahd","Universidad de Qatar","Universidad de Emiratos Árabes Unidos","Universidad Khalifa",
    "Universidad de Sharjah","Universidad de Jordania","Universidad Americana de Beirut","Universidad de Teherán",
    "Universidad Tecnológica de Sharif","Universidad Amirkabir de Tecnología","Universidad de Ciencia y Tecnología de Irán",
    "Universidad de São Paulo","Universidad Estatal de Campinas","Universidad Estatal Paulista","Universidad Federal de Río de Janeiro",
    "Universidad Federal de Minas Gerais","Universidad Federal de Río Grande del Sur","Universidad Federal de São Paulo",
    "Universidad Federal de Santa Catarina","Pontificia Universidad Católica de Chile","Universidad de Chile","Universidad de los Andes",
    "Universidad Nacional de Colombia","Universidad de Buenos Aires","Universidad Nacional Autónoma de México",
    "Instituto Tecnológico y de Estudios Superiores de Monterrey","Universidad de Guadalajara","Universidad de Costa Rica",
    "Universidad de la República","Universidad de Antioquia","Universidad del Rosario","Universidad Pontificia Bolivariana",
    "Universidad del Valle","Universidad de La Sabana","Universidad de Concepción","Universidad Técnica Federico Santa María",
    "Universidad de Santiago de Chile","Universidad Adolfo Ibáñez","Universidad Austral de Chile","Universidad de Talca",
    "Universidad de La Frontera","Universidad Nacional de La Plata","Universidad Nacional de Córdoba","Universidad Nacional de Rosario",
    "Universidad Nacional de Cuyo","Universidad Nacional del Sur","Universidad de Belgrano","Universidad Torcuato Di Tella",
    "Universidad de San Andrés","Universidad Tecnológica Nacional","Universidad Autónoma Metropolitana","Universidad Iberoamericana",
    "Universidad Anáhuac","Instituto Politécnico Nacional","Universidad Autónoma de Nuevo León","Universidad Autónoma de Puebla",
    "Universidad Autónoma de Guadalajara","Universidad Panamericana","Universidad de Lima","Pontificia Universidad Católica del Perú",
    "Universidad Peruana Cayetano Heredia","Universidad del Pacífico","Universidad de San Martín de Porres","Universidad de Piura",
    "Universidad de los Andes Chile","Universidad Católica del Norte","Universidad Diego Portales","Universidad Mayor",
    "Universidad San Sebastián","Universidad Andrés Bello","Universidad de Valparaíso","Universidad de Magallanes",
    "Universidad Católica de Córdoba","Universidad Católica Argentina","Universidad Austral Argentina","Universidad de Palermo",
    "Universidad de Montevideo","Universidad ORT Uruguay","Universidad Católica del Uruguay","Universidad de la Habana",
    "Universidad Tecnológica de La Habana","Universidad de Puerto Rico","Universidad de Santo Tomás","Universidad de Filipinas",
    "Universidad Ateneo de Manila","Universidad de Santo Tomás Filipinas","Universidad De La Salle Manila","Universidad de Indonesia",
    "Universidad Gadjah Mada","Instituto Tecnológico de Bandung","Universidad de Malasia Sabah","Universidad de Malasia Sarawak",
    "Universidad Tecnológica MARA","Universidad Thammasat","Universidad Kasetsart","Universidad de Khon Kaen","Universidad de Prince of Songkla",
    "Universidad Tecnológica de Suranaree","Universidad de Ciencia y Tecnología de Hanoi","Universidad Nacional de Vietnam en Hanoi",
    "Universidad Nacional de Vietnam en Ciudad Ho Chi Minh","Universidad Chulalongkorn","Universidad Mahidol","Universidad de Yangon",
    "Universidad de Colombo","Universidad de Peradeniya","Universidad de Dhaka","Universidad de Ingeniería y Tecnología de Bangladesh",
    "Universidad de Karachi","Universidad de Lahore","Universidad de Punjab","Universidad Quaid-i-Azam","Universidad de Delhi",
    "Universidad Jawaharlal Nehru","Instituto Indio de Ciencia","Instituto Indio de Tecnología de Bombay","Instituto Indio de Tecnología de Delhi",
    "Instituto Indio de Tecnología de Madrás","Instituto Indio de Tecnología de Kanpur","Instituto Indio de Tecnología de Kharagpur",
    "Instituto Indio de Tecnología de Roorkee","Instituto Indio de Tecnología de Guwahati","Instituto Indio de Tecnología de Hyderabad",
    "Instituto Indio de Tecnología de Indore",

    #500家公司
    "Wal-Mart Stores","Saudi Arabian Oil Company","State Grid Corporation of China","Amazon.com","China National Petroleum Corporation",
    "China Petroleum and Chemical Corporation","Exxon Mobil Corporation","Apple","Shell","UnitedHealth Group","CVS Health Corporation",
    "Berkshire Hathaway","Alphabet","McKesson Corporation","Toyota Motor Corporation","Glencore","Trafigura Group",
    "China State Construction Engineering Corporation","Samsung Electronics","Costco Wholesale Corporation","Hon Hai Precision Industry Company",
    "Industrial and Commercial Bank of China","China Construction Bank","Agricultural Bank of China","Bank of China","Microsoft Corporation",
    "Ping An Insurance Group Company of China","China Mobile Communications Group","China Railway Engineering Group",
    "China Railway Construction Corporation","Volkswagen","China National Offshore Oil Corporation","China Life Insurance Company",
    "Sinochem Holdings Corporation","China Baowu Steel Group","AT&T","TotalEnergies","Ford Motor Company","Mercedes-Benz Group",
    "China Communications Construction Company","Honda Motor Company","CITIC Group Corporation","China Resources Company","Électricité de France",
    "Gazprom","Deutsche Telekom","BMW Group","China Southern Power Grid","China Post Group","Power Construction Corporation of China",
    "China Energy Engineering Group","Walgreens Boots Alliance","JD.com","Kroger","China Minmetals Corporation",
    "China North Industries Group Corporation","Federal National Mortgage Association","CRRC Corporation",
    "China United Network Communications Group","Target Corporation","Allianz","China Electronics Technology Group",
    "China COSCO Shipping Corporation","Aviation Industry Corporation of China","China Aerospace Science and Technology Corporation",
    "China Aerospace Science and Industry Corporation","China Electronics Corporation","Aviva","Nippon Telegraph and Telephone Corporation",
    "China National Coal Group","China Huaneng Group","China Huadian Corporation","China Datang Corporation","China Energy Investment Corporation",
    "China General Nuclear Power Group","China Three Gorges Corporation","China Energy Conservation and Environmental Protection Group",
    "China Chengtong Holdings Group","China Reform Holdings Corporation","China Nonferrous Metal Mining Group","China National Gold Group",
    "China Forestry Group","China Southern Airlines Group","China Eastern Airlines Group","Air China Group","China General Technology Group",
    "China Poly Group Corporation","China Tourism Group","Sinopharm","China National Machinery Industry Corporation",
    "China National Building Material Group","Sinosteel Corporation","Aluminum Corporation of China","China National Chemical Engineering Group",
    "China Metallurgical Group Corporation","China Salt Industry Group","China Logistics Group","China Grain Reserves Corporation",
    "JPMorgan Chase","Bank of America","China Everbright Group","China Taiping Insurance Group","People’s Insurance Company Group of China",
    "China Reinsurance Group","China Everbright Bank","China Minsheng Banking Corporation","Postal Savings Bank of China","Bank of Communications",
    "Shanghai Pudong Development Bank","Industrial Bank","China Merchants Bank","China CITIC Bank","Huaxia Bank","Bank of Beijing",
    "Bank of Shanghai","Bank of Jiangsu","Bank of Nanjing","Bank of Ningbo","Bank of Guangzhou","China Bohai Bank","Bank of Tianjin",
    "Harbin Bank","Shengjing Bank","Bank of Chongqing","Bank of Chengdu","Bank of Changsha","Huishang Bank","Bank of Qingdao","Bank of Zhengzhou",
    "Bank of Lanzhou","Bank of Xi’an","Bank of Guiyang","Kunlun Bank","Bank of Dalian","Bank of Jilin","Baoshang Bank","Bank of Jinzhou",
    "Hengfeng Bank","Standard Chartered","HSBC Holdings","Barclays","Deutsche Bank","BNP Paribas","UBS Group","Credit Suisse Group","ING Group",
    "Intesa Sanpaolo","Banco Santander","Banco Bilbao Vizcaya Argentaria","Mizuho Financial Group","Mitsubishi UFJ Financial Group",
    "Sumitomo Mitsui Financial Group","Nomura Holdings","Dai-ichi Life Holdings","Tokio Marine Holdings","Japan Post Holdings",
    "Nippon Life Insurance Company","Sumitomo Life Insurance Company","Meiji Yasuda Life Insurance Company","Wells Fargo","Goldman Sachs Group",
    "Morgan Stanley","Citigroup","American Express","American International Group","MetLife","Prudential Financial","Cigna Group","AXA",
    "Assicurazioni Generali","Munich Reinsurance Company","Zurich Insurance Group","Prudential","AIA Group","China Pacific Insurance Group",
    "New China Life Insurance Company","Taikang Insurance Group","Sunshine Insurance Group","China Huarong Asset Management",
    "China Cinda Asset Management","China Orient Asset Management","China Great Wall Asset Management","Guotai Junan Securities",
    "CITIC Securities","Haitong Securities","Huatai Securities","China Merchants Securities","Shenwan Hongyuan Group","GF Securities",
    "Orient Securities","China International Capital Corporation","Everbright Securities","Guosen Securities","Ping An Securities",
    "China Galaxy Securities","Dongxing Securities","Intel Corporation","Nvidia Corporation","Oracle Corporation","Cisco Systems",
    "Qualcomm","Broadcom","Dell Technologies","Hewlett-Packard Company","International Business Machines Corporation","Adobe",
    "Texas Instruments","Applied Materials","Micron Technology","ASML Holding","Taiwan Semiconductor Manufacturing Company","MediaTek",
    "Sony Group Corporation","Panasonic Holdings Corporation","Hitachi","Toshiba Corporation","Mitsubishi Electric Corporation",
    "Fujitsu","Canon","Ricoh","Seiko Epson Corporation","LG Electronics","SK Hynix","Hyundai Motor Company","Kia Corporation","Renault Group",
    "Stellantis","Volvo Group","Volvo Car Corporation","Tata Motors","Suzuki Motor Corporation","Mazda Motor Corporation","Subaru Corporation",
    "Great Wall Motor Company","Geely Automobile Holdings","BYD Company","SAIC Motor Corporation","Guangzhou Automobile Group",
    "Dongfeng Motor Corporation","FAW Group Corporation","BAIC Group","NIO","XPeng","Li Auto","Tesla","Boeing","Airbus",
    "Lockheed Martin Corporation","Raytheon Technologies Corporation","Northrop Grumman Corporation","General Dynamics",
    "Honeywell International","3M Company","Caterpillar","Deere & Company","Siemens","General Electric","Schneider Electric","ABB",
    "Philips","Emerson Electric","Eaton Corporation","Rockwell Automation","Danaher Corporation","Thermo Fisher Scientific","PepsiCo",
    "Coca-Cola Company","Nestlé","Procter & Gamble","Unilever","L'Oréal","Estée Lauder Companies","Nike","Adidas","Puma","Fast Retailing",
    "Kering","LVMH Moët Hennessy Louis Vuitton","Chanel","IKEA","Home Depot","Lowe's Companies","Best Buy","McDonald's","Yum! Brands",
    "Starbucks","Domino's Pizza","Anheuser-Busch InBev","Heineken","Carlsberg","Diageo","Pernod Ricard","Medtronic","Abbott Laboratories",
    "Johnson & Johnson","Pfizer","Merck & Co.","AstraZeneca","GlaxoSmithKline","Novartis","Roche Holding","Eli Lilly and Company",
    "Bayer","Sanofi","Takeda Pharmaceutical Company","Amgen","Biogen","Gilead Sciences","Regeneron Pharmaceuticals","Illumina",
    "Walgreens Boots Alliance","AmerisourceBergen","Cardinal Health","United Parcel Service","FedEx","Deutsche Post","Japan Post Holdings",
    "SF Holding","ZTO Express","YTO Express Group","STO Express","Yunda Holding","Deppon Logistics","JD Logistics","Cainiao Network Technology",
    "Alibaba Group Holding","Tencent Holdings","ByteDance","Baidu","Xiaomi Corporation","Meituan","Pinduoduo","NetEase","Bilibili","DiDi Global",
    "Grab Holdings","Sea Limited","Booking Holdings","Airbnb","Uber Technologies","Lyft","Expedia Group","Trip.com Group",
    "Marriott International","Hilton Worldwide Holdings","InterContinental Hotels Group","Accor","Hyatt Hotels Corporation",
    "Wyndham Hotels and Resorts","Shangri-La Asia","Fosun International","Greenland Holding Group","Country Garden Holdings",
    "China Vanke","Evergrande Group","Longfor Group Holdings","China Resources Land","Poly Developments and Holdings Group",
    "China Merchants Shekou Industrial Zone Holdings","Shimao Group Holdings","Sunac China Holdings","China Oceanwide Holdings",
    "Agile Group Holdings","CIFI Holdings Group","Zhongliang Holdings Group","Powerlong Real Estate Holdings","Gemdale Corporation",
    "C&D Real Estate Corporation","Yuexiu Property","KWG Group Holdings","China Aoyuan Group","Seazen Group","China Jinmao Holdings",
    "China Overseas Land and Investment","Overseas Chinese Town Enterprises","Beijing Capital Group","Beijing Urban Construction Group",
    "Bright Food Group","COFCO Corporation","Wilmar International","Mengniu Dairy","Yili Group","Wahaha Group","Nongfu Spring",
    "Uni-President China Holdings","Tingyi Cayman Islands Holding","Inditex","H&M Hennes & Mauritz","Lululemon Athletica","Under Armour",
    "Richemont","Swatch Group","Hermès International","Burberry Group","Tapestry","Capri Holdings","American Eagle Outfitters","Gap","PVH",
    "Ralph Lauren","Levi Strauss & Co.","VF Corporation","Colgate-Palmolive","Kimberly-Clark","Clorox","Church & Dwight","Reckitt Benckiser",
    "Estee Lauder Companies","Shiseido Company","Kao Corporation","Amorepacific Corporation","LG Household & Health Care",
    "Shandong Weigao Group","Mindray Bio-Medical Electronics","WuXi AppTec","China Medical System Holdings","China Resources Pharmaceutical Group",
    "Shanghai Pharmaceuticals Holding","Sinopharm Holding","CSPC Pharmaceutical Group","Hengrui Medicine","Hansoh Pharmaceutical Group",
    "China Feihe","Tsingtao Brewery","China Resources Beer","Budweiser Brewing Company APAC","Kweichow Moutai","Wuliangye Yibin","Luzhou Laojiao",
    "Yanghe Distillery","Shanxi Xinghuacun Fen Wine Factory","Beijing Yanjing Brewery","Mengniu Dairy","Yili Industrial Group",
    "Bright Dairy & Food","China Mengniu Dairy",

]